### ISSUE TITLE
Add as contributor? Also, getting odd failure

### ISSUE THREAD

**Issue by mohawk2** [kazuakiyama/homebrew-pgplot#5]
Hi, thank you for taking this on after the "core" formula was removed!

At @PDLPorters we've been using this for our CI on MacOS. Trying to fix it on my machine, I'm seeing https://github.com/kazuakiyama/homebrew-pgplot/blob/d5b597935b3128b88a08ea99ee62f1d64f94df05/pgplot.rb#L41
produces an error of no `to_f` found on a class starting `void::Private...`.

It looks to me like the more idiomatic way to achieve picking behaviour based on OS version, from https://docs.brew.sh/Formula-Cookbook#inside-def-install-and-test-do, is to use something like:

```ruby
if MacOS.version >= 13.0
```

If you're happy to add me as a contributor, I can add this myself.

**Comment by kazuakiyama** [comment]
Hi @mohawk2, thanks a lot for pointing this out. I'm glad that this formula has been used for @PDLPorters, which I did not certainly expect :). This is a quick fix that can be done on my side, so I will do it sometime in the next few hours. Anyway, I'd be happy to add you to the contributor as I'm not a frequent maintainer for this particular formula.

**Comment by kazuakiyama** [comment]
OK, I fixed the issue. It turns out that brew only accepts symbolic expression `if MacOS.version >= :ventura` rather than `if MacOS.version >= 13.0`. New revision 13 has been released to reflect the fix. I will add you to a contributor.
https://github.com/kazuakiyama/homebrew-pgplot/releases

**Comment by kazuakiyama** [comment]
@mohawk2 I've closed this issue as the updated formula was confirmed to work in both Intel- and ARM-based macOS 14. Please reopen the issue if you see an issue with this update. I invited you to this repository so that you can make a fix on your own.
